jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          pytest -v

workflows:
  version: 2
  run_test:
    jobs:
      - test